// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1aFcDr0pJMaxTp8irwQgI_F6FikNydt0',
    appId: '1:203555324438:web:2a243642d96834e2692b37',
    messagingSenderId: '203555324438',
    projectId: 'litspetcra',
    authDomain: 'litspetcra.firebaseapp.com',
    storageBucket: 'litspetcra.appspot.com',
    measurementId: 'G-323GQJ4BS7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgvCayf_UO1GahRaMNRbCusSqIPYrurk8',
    appId: '1:203555324438:android:efef5b2354c51792692b37',
    messagingSenderId: '203555324438',
    projectId: 'litspetcra',
    storageBucket: 'litspetcra.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkfAFZUKF6tq_KP84G0S_VgAMRHHmwQO8',
    appId: '1:203555324438:ios:07ca4a1c980e76b0692b37',
    messagingSenderId: '203555324438',
    projectId: 'litspetcra',
    storageBucket: 'litspetcra.appspot.com',
    iosBundleId: 'com.example.nigger',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCkfAFZUKF6tq_KP84G0S_VgAMRHHmwQO8',
    appId: '1:203555324438:ios:07ca4a1c980e76b0692b37',
    messagingSenderId: '203555324438',
    projectId: 'litspetcra',
    storageBucket: 'litspetcra.appspot.com',
    iosBundleId: 'com.example.nigger',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD1aFcDr0pJMaxTp8irwQgI_F6FikNydt0',
    appId: '1:203555324438:web:d5764aefc41adb4c692b37',
    messagingSenderId: '203555324438',
    projectId: 'litspetcra',
    authDomain: 'litspetcra.firebaseapp.com',
    storageBucket: 'litspetcra.appspot.com',
    measurementId: 'G-7HHXQVYQ9T',
  );
}
